---
# tasks file for initial_configuration
- name: "Sudoers"
  lineinfile:
    path: "/etc/sudoers"
    insertafter: '^root'
    line: 'adminUsername        ALL=(ALL)       NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: "Actualizacion del Sistema al ultimo nivel"
  dnf:
    name: "*"
    state: latest

- name: "Configuramos zona horaria"
  timezone:
    name: Europe/Madrid

- name: "Instalacion paqueteria"
  dnf:
    name: 
      - chrony
      - nfs-utils 
      - nfs4-acl-tools 
      - wget
      - iproute-tc
    state: present

- name: "Habilitar y arrancar chrony"
  service:
    name: chronyd
    state: started
    enabled: true
    daemon_reload: true

- name: "Habilitar NTP"
  command: timedatectl set-ntp true
  register: rc

- name: "Debug NTP"
  fail:
    msg: "ERROR - Fallo en la configuracion de NTP"
  when: rc.rc != 0

- name: "Desactivar Selinux"
  replace:
    path: /etc/selinux/config
    regexp: '=enforcing'
    replace: '=disabled'
    backup: yes

- name: "Comprobar necesidad de reinicio"
  command: needs-restarting -r
  register: needs_reboot
  ignore_errors: yes

- name: "Debug NEEDS-RESTARTING"
  debug:
    var: needs_reboot.rc

# async y poll para permitir desengancharse
- name: "Reinicio del Servidor"
  command: shutdown -r now
  async: 30
  poll: 0
  when: needs_reboot.rc == 1

- name: "Cierre de conexion"
  pause: 
    seconds: 30
  when: needs_reboot.rc == 1

- name: "PAUSA"
  pause:
    seconds: 60
