- hosts: all
  gather_facts: false
  tasks:

    - name: "JOIN CLUSTER - Copiar fichero"
      copy: 
        src: "/home/pablo/ansible/kubeadm.txt" 
        dest: "/home/adminUsername/kubeadm-join"
        mode: 0774

    - name: "JOIN CLUSTER - Ejecutar join"
      shell: "sh /home/adminUsername/kubeadm-join"
      become: true
