---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:

    - name: "TERRAFORM - Destruccion de la infraestrucura."
      shell: "terraform destroy -auto-approve=true"
      register: terraform_destroy_rc
      args:
        chdir: "{{ terraform_path }}"
      tags: 
      - terraform_destroy

    - name: "TERRAFORM - DEBUG - Destruccion de la infraestrucura."
      fail:
        msg: "TERRAFORM - Se ha producido un error a la hora de destruir la infraestructura con terraform."
      when: terraform_destroy_rc.rc!= 0
      tags:
      - terraform_destroy

    - name: "TERRAFORM - Despliegue de la infraestrucura."
      shell: "terraform apply -auto-approve=true"
      register: terraform_apply_rc
      args:
        chdir: "{{ terraform_path }}"
      tags:
      - terraform_apply

    - name: "TERRAFORM - DEBUG - Despliegue de la infraestrucura."
      fail:
        msg: "TERRAFORM - Se ha producido un error en el despliegue de la infraestructura con terraform."
      when: terraform_apply_rc.rc != 0
      tags:
      - terraform_apply
