---
# tasks file for deploy_nfs
- name: "Obtener el disco dado"
  shell: "lsblk | grep 'disk' | grep '{{ disk_gb }}G' | awk '{print $1}'"
  register: disk

- name: "DEBUG - disco"
  debug:
    msg: "DISCO: {{ disk.stdout }}"

- name: "LVG - Creacion de LVG"
  lvg:
    vg: vg_nfs
    pvs: "/dev/{{ disk.stdout }}"

- name: "LVOL - Crear LVOL sobre LVG"
  lvol:
    vg: vg_nfs
    lv: lv_nfs
    size: 5120

- name: "FILESYSTEM | Crear FS sobre el LVOL"
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_nfs-lv_nfs
    force: true

- name: "MOUNT | Montar FS"
  mount:
    path: /srv/nfs
    src: /dev/mapper/vg_nfs-lv_nfs
    fstype: xfs
    state: mounted
    opts: defaults

- name: "Instalacion paqueteria"
  dnf:
    name:
      - net-tools
      - nfs-utils
    state: present

- name: "Habilitar y arrancar nfs-server"
  service:
    name: nfs-server
    state: started
    enabled: true
    daemon_reload: true

- name: "Creacion del fichero exports"
  copy:
    dest: /etc/exports
    content: |
      /srv/nfs	10.0.1.11(rw,sync)
      /srv/nfs	10.0.1.12(rw,sync)
    mode: 0644
    owner: root
    group: root

- name: "Recargar el fichero exports"
  command: "exportfs -r"
  register: exports

- name: "DEBUG - exports"
  fail:
    msg: "DEBUG - Fallo en la recarga del fichero exports"
  when: exports.rc != 0

- name: "Firewall"
  firewalld:
    zone: dmz
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: "Recargar servicio firewalld"
  service:
    name: firewalld
    state: restarted
    enabled: true
    daemon_reload: true

