---
# tasks file for common_tasks
- name: "Creacion fichero hosts"
  copy:
    dest: /etc/hosts
    content: |
      10.0.1.10 vm-master vm-master.kubernetes-domain.com
      10.0.1.20 vm-nfs vm-nfs.kubernetes-domain.com
      10.0.1.30 vm-worker01 vm-worker01.kubernetes-domain.com
      10.0.1.40 vm-worker02 vm-worker02.kubernetes-domain.com
    mode: 0644
    owner: root
    group: root

- name: "Aseguramos servicio firewalld"
  service:
    name: firewalld
    state: started
    enabled: true
    daemon_reload: true

- name: "Habilitar transparent masquerading"
  shell: "modprobe br_netfilter && firewall-cmd --add-masquerade --permanent &&  firewall-cmd --reload"
  register: transparent

- name: "DEBUG - transparent masquerading"
  fail:
    msg: "DEBUG - Se ha producido un fallo a la hora de habilitar transparent masquerading"
  when: transparent.rc != 0

- name: "Creacion fichero k8s.conf"
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
    mode: 0644
    owner: root
    group: root

- name: "Fichero k8s.conf"
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: "Desactivamos la SWAP"
  command: swapoff -a
  register: swap

- name: "DEBUG - SWAP"
  fail:
    msg: "DEBUG - Se ha producido un fallo a la hora de deshabilitar la SWAP"
  when: swap.rc != 0

- name: "Eliminamos la SWAP del fichero /etc/fstab"
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: true

- name: "Repositorio de docker"
  shell: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  register: repo_add

- name: "DEBUG - Repositorio Docker"
  fail:
    msg: "DEBUG - Se ha producido un fallo a la hora de habilitar el repositorio de docker"
  when: repo_add.rc != 0

- name: "Instalacion de paqueteria docker"
  dnf:
    name: docker-ce
    state: latest

- name: "Arrancar y habilitar docker"
  service:    
    name: docker
    state: started
    enabled: true
    daemon_reload: true

- name: "Repositorio de kubernetes"
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: true
    enabled: true
    repo_gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

- name: "Instalacion kubernetes"
  dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  with_items:
   - kubelet
   - kubeadm
   - kubectl

- name: "Arrancar y habilitar kubelet"
  service:
    name: kubelet
    state: started
    enabled: true
    daemon_reload: true

