---
- name: "Montaje de exports"
  hosts: all
  become: true
  tasks:

    - name: Mount an NFS volume
      mount:
        src: 10.0.1.10:/srv/nfs
        path: /srv/nfs
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs
