---
- name: "Paso 5 - Tareas de post-configuracion"
  hosts: master,workers
  become: true
  tasks:
    - name: "PUERTOS - Apertura de puertos para la SDN"
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 8285/udp
        - 8472/udp

    - name: "FIREWALD - Reinicio"
      service:
        name: firewalld
        state: restarted

- name: "Paso 6 - Despliegue SDN"
  hosts: master
  become: true
  tasks:
    - name: "SDN - Despliegue desde fichero"
      command: "kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml"
      register: kubectl_sdn

    - name: "DEBUG - SDN calico"
      fail:
        msg: "ERROR - Se ha producido un error en el despliegue de la SDN"
      when: kubectl_sdn.rc != 0
