---
- name: "Paso 2 - Despliegue NFS"
  hosts: all
  become: true

  pre_tasks:
    - debug:
        msg: 'DEBUG - Iniciando el despliegue del servidor NfS.'

  roles:
    - deploy_nfs

  post_tasks:
    - debug:
        msg: 'DEBUG - Despliegue del servidor nfs finalizado.'
