---
- hosts: all
  gather_facts: false
  tasks:

    - name: "Comprobar disponibilidad del Servidor"
      local_action: wait_for host={{ inventory_hostname }} port=22
        state=started delay=30 timeout=300
      retries: 60
      delay: 20
